# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: 'bitnami/mongodb:latest'
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: mongo
      MONGODB_DATABASE: jobz
      MONGODB_ROOT_USER: mongo
      MONGODB_ROOT_PASSWORD: mongo
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      # MONGODB_ADVERTISED_HOSTNAME: mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
      